name: Dockcross Action Sandbox
on:
  workflow_dispatch:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: pull dockcross
        run: docker build -f 00-HelloWorld/Dockerfile -t myimage00 .

      - name: get helper script
        run: |
          docker run --rm myimage00 > ./dockcross
          chmod +x ./dockcross

      - name: build 00-HelloWorld
        run: |
          cd 00-HelloWorld
          echo "$CC"
          ./dockcross bash -c "echo '$CC'"
          ../dockcross bash -c "pip install ."

      - name: test
        run : |
          ./dockcross python3 00-HelloWorld/test.py