name: Dockcross Action Sandbox
on:
  workflow_dispatch:
  push:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: pull dockcross
        run: docker build -f 00-HelloWorld/Dockerfile -t my image00 .

      - name: get helper script
        run: |
          docker run --rm myimage00 > ./dockcross
          chmod +x ./dockcross

      - name: build 00-HelloWorld
        run: |
          cd 00-HelloWorld
          ../dockcross pip install .